# https://github.com/srcery-colors/srcery-terminal/

# Colors (Srcery)
colors:
  # Default colors
  primary:
    background: "#1c1b19"
    foreground: "#fce8c3"

  # Cursor colors
  cursor:
    text: CellBackground
    cursor: "#fbb829"

  # Normal colors
  normal:
    black: "#1c1b19"
    red: "#ef2f27"
    green: "#519f50"
    yellow: "#fbb829"
    blue: "#2c78bf"
    magenta: "#e02c6d"
    cyan: "#0aaeb3"
    white: "#baa67f"

  # Bright colors
  bright:
    black: "#918175"
    red: "#f75341"
    green: "#98bc37"
    yellow: "#fed06e"
    blue: "#68a8e4"
    magenta: "#ff5c8f"
    cyan: "#2be4d0"
    white: "#fce8c3"

window.opacity: 1

font:
  normal:
    family: "JetBrains Mono"
    style: Regular
  size: 12.0
  offset:
    x: 0
    y: 0
  glyph_offset:
    x: 0
    y: 0
  draw_bold_text_with_bright_colors: true

window:
  padding:
    x: 2
    y: 2
  dimensions:
    columns: 100
    lines: 24
  decorations: none

cursor:
  style: beam

env:
  TERM: xterm-256color

scrolling:
  history: 10000
  multiplier: 5

selection:
  semantic_escape_chars: ',│`|:"'' ()[]{}<>'
  save_to_clipboard: true

live_config_reload: true
hide_cursor_when_typing: true

url:
  launcher: open
  modifiers: Shift

key_bindings:
  - { key: Key0, mods: Control, action: ResetFontSize }
  - { key: Plus, mods: Control, action: IncreaseFontSize }
  - { key: Minus, mods: Control, action: DecreaseFontSize }
