# https://github.com/srcery-colors/srcery-terminal/

colors:
  primary:
    background: &gruvbox_dark_bg "#282828"
    foreground: "#ebdbb2"
    bright_foreground: "#fbf1c7"
    dim_foreground: "#a89984"
  cursor:
    text: CellBackground
    cursor: CellForeground

  vi_mode_cursor:
    text: CellBackground
    cursor: CellForeground

  selection:
    text: CellBackground
    background: CellForeground

  bright:
    black: "#928374"
    red: "#fb4934"
    green: "#b8bb26"
    yellow: "#fabd2f"
    blue: "#83a598"
    magenta: "#d3869b"
    cyan: "#8ec07c"
    white: "#ebdbb2"

  normal:
    black: *gruvbox_dark_bg
    red: "#cc241d"
    green: "#98971a"
    yellow: "#d79921"
    blue: "#458588"
    magenta: "#b16286"
    cyan: "#689d6a"
    white: "#a89984"

  dim:
    black: "#32302f"
    red: "#9d0006"
    green: "#79740e"
    yellow: "#b57614"
    blue: "#076678"
    magenta: "#8f3f71"
    cyan: "#427b58"
    white: "#928374"

window.opacity: 1

font:
  normal:
    family: "JetBrains Mono"
    style: Regular
  size: 12.0
  offset:
    x: 0
    y: 0
  glyph_offset:
    x: 0
    y: 0
  draw_bold_text_with_bright_colors: true

window:
  padding:
    x: 2
    y: 2
  dimensions:
    columns: 100
    lines: 24
  decorations: none

cursor:
  style: beam

env:
  TERM: xterm-256color

scrolling:
  history: 10000
  multiplier: 5

selection:
  semantic_escape_chars: ',│`|:"'' ()[]{}<>'
  save_to_clipboard: true

live_config_reload: true
hide_cursor_when_typing: true

url:
  launcher: open
  modifiers: Shift

key_bindings:
  - { key: Key0, mods: Control, action: ResetFontSize }
  - { key: Plus, mods: Control, action: IncreaseFontSize }
  - { key: Minus, mods: Control, action: DecreaseFontSize }
