theme = "gruvbox"

[editor]
scrolloff = 3
mouse = true
middle-click-paste = true
scroll-lines = 3
shell = ["dash", "-c"]
line-number = "absolute"
auto-completion = true
idle-timeout = 400
completion-trigger-len = 2
auto-info = true
true-color = false

[editor.lsp]
display-messages = false

[editor.cursor-shape]
normal = "underline"
insert = "bar"
select = "block"

[editor.file-picker]
hidden = true
parents = true
ignore = true
git-ignore = true
git-global = true
git-exclude = true

[editor.search]
smart-case = true
wrap-around = true

[keys.normal]
C-S-i = ":format"

[keys.insert]
C-right = "move_next_word_start"